# Generated by Django 4.2.1 on 2023-05-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinemas", "0002_reservation_room_seat_showtime_tickets_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tickets",
            new_name="Ticket",
        ),
        migrations.RenameField(
            model_name="showtime",
            old_name="move",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="seats",
            new_name="seat",
        ),
    ]
