# Generated by Django 4.2.1 on 2023-05-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinemas", "0004_alter_showtime_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cinemas.seat"
            ),
        ),
    ]
